// 200-point technician inspections for trucks (horses/rigids) and trailers.
// 20 sections x 10 points each. Item ids are stable: changing a label is safe,
// changing an id breaks history for saved job cards.

const sec = (prefix, id, title, labels) => ({
  id: `${prefix}_${id}`,
  title,
  items: labels.map((label, i) => ({
    id: `${prefix}_${id}_${String(i + 1).padStart(2, "0")}`,
    label,
  })),
});

const T = "i200t";
export const TRUCK_200_SECTIONS = [
  sec(T, "docs", "Documentation & Identification", [
    "Licence disc valid and displayed",
    "Roadworthy / COF certificate valid",
    "Operator card (PrDP operator) valid and displayed",
    "Registration plates secure, clean and legible (front & rear)",
    "VIN / chassis number matches documents",
    "Engine number matches documents",
    "Odometer / hour meter reading recorded",
    "Service history and previous job cards reviewed",
    "Open defect reports and recalls checked",
    "Insurance and permits (cross-border / DG / abnormal) on board where required",
  ]),
  sec(T, "diag", "Diagnostics & Instruments", [
    "Full diagnostic scan done — fault codes recorded",
    "Active faults resolved or logged on job card",
    "Dashboard warning lights self-test on start-up",
    "Speedometer and odometer working",
    "Tachograph / vehicle tracking unit working and sealed",
    "Speed limiter set and sealed to legal limit",
    "Air pressure gauges accurate (dual circuit)",
    "Oil pressure and temperature gauges working",
    "Fuel and AdBlue gauges working",
    "Telematics / camera system powered and recording",
  ]),
  sec(T, "englube", "Engine — Lubrication & Mechanical", [
    "Engine oil level and condition",
    "Oil filter condition / replaced per schedule",
    "Oil leaks — sump, rocker cover, front and rear seals",
    "Oil sample drawn for analysis (where scheduled)",
    "Engine mounts secure, rubbers not perished",
    "Abnormal engine noise or knocking",
    "Blow-by / crankcase breather condition",
    "Valve clearance adjusted (where due)",
    "Timing cover and front pulley condition",
    "Engine idles smoothly at correct speed",
  ]),
  sec(T, "intake", "Engine — Air Intake & Exhaust", [
    "Air filter element and restriction indicator",
    "Pre-cleaner / dust bowl clean",
    "Intake hoses and clamps secure, no cracks",
    "Turbocharger — shaft play, oil leaks, noise",
    "Intercooler core and hoses — leaks and blockages",
    "Exhaust manifold and gaskets — no leaks",
    "Exhaust pipes, mountings and silencer secure",
    "DPF / after-treatment system condition",
    "AdBlue (DEF) level, lines and dosing system",
    "Exhaust smoke colour and density acceptable",
  ]),
  sec(T, "fuel", "Fuel System", [
    "Fuel tank(s) secure, straps and mountings",
    "Fuel tank cap(s) sealing and lockable",
    "Fuel lines and fittings — leaks and chafing",
    "Primary fuel filter / water separator drained",
    "Secondary fuel filter condition / replaced",
    "Lift pump operation",
    "Injector leak-off and injector lines",
    "Fuel tank breather clear",
    "Anti-siphon device fitted and intact",
    "No fuel contamination (water / sediment)",
  ]),
  sec(T, "cool", "Cooling System", [
    "Coolant level and concentration",
    "Radiator core — clean, no damage or leaks",
    "Radiator and heater hoses — condition and clamps",
    "Water pump — leaks and bearing play",
    "Thermostat operation (warm-up time)",
    "Viscous / electric fan operation",
    "Fan shroud secure and intact",
    "Expansion tank and pressure cap",
    "Coolant temperature sensor working",
    "Cab heater and demister operation",
  ]),
  sec(T, "charge", "Electrical — Charging & Starting", [
    "Batteries — condition, electrolyte, secure",
    "Battery terminals clean and tight",
    "Battery isolator switch working",
    "Alternator charging output within range",
    "Alternator and drive belt condition / tension",
    "Starter motor operation",
    "Main cables — chafing, heat damage, routing",
    "Fuses and relays — correct ratings, no corrosion",
    "Earth straps secure and clean",
    "Trailer electrical sockets (24V) clean and working",
  ]),
  sec(T, "lights", "Lighting & Signalling", [
    "Headlamps — dipped beam",
    "Headlamps — main beam and aim",
    "Front position / parking lamps",
    "Direction indicators — front, side and rear",
    "Hazard warning lamps",
    "Stop / brake lamps",
    "Tail lamps",
    "Number plate lamp",
    "Reverse lamp and reverse alarm",
    "Rotating beacon / amber strobe (mine or site spec)",
  ]),
  sec(T, "gearbox", "Clutch, Gearbox & Retarder", [
    "Clutch operation, free play and slip test",
    "Clutch fluid / air assist — leaks",
    "Gearbox oil level",
    "Gearbox oil leaks",
    "Gear selection — all ranges, no jumping out",
    "AMT / automated gearbox calibration and faults",
    "Gearbox mountings secure",
    "Retarder / exhaust brake operation",
    "PTO operation and engagement (where fitted)",
    "Gear lever and linkages — wear and play",
  ]),
  sec(T, "driveline", "Driveline & Axles", [
    "Propshaft condition and balance",
    "Universal joints — play and greasing",
    "Centre bearing and mounting",
    "Differential oil level(s)",
    "Differential and hub oil leaks",
    "Diff lock / inter-axle lock operation",
    "Wheel bearings — play and noise",
    "Hub seals — no leaks",
    "Axle housings — cracks and damage",
    "Driveshaft guards / safety loops fitted",
  ]),
  sec(T, "airbrake", "Brakes — Air System", [
    "Compressor build-up time within spec",
    "Governor cut-in and cut-out pressures",
    "Air dryer and cartridge condition",
    "Air tanks drained — no oil or water",
    "Air leak test — full system at rest",
    "Air leak test — brakes applied",
    "Low-pressure warning activates correctly",
    "Air lines and fittings — chafing and security",
    "Trailer supply and service couplings (palm couplings) and seals",
    "Protection valves / four-circuit valve operation",
  ]),
  sec(T, "brakefound", "Brakes — Foundation", [
    "Service brake efficiency (brake test)",
    "Park brake holds on gradient / test",
    "Emergency / secondary brake operation",
    "Brake linings / pads — thickness, front axle",
    "Brake linings / pads — thickness, drive axle(s)",
    "Drums / discs — cracks, scoring, wear",
    "Brake chambers and spring brakes — condition and leaks",
    "Slack adjusters — stroke within limits",
    "ABS / EBS warning and function",
    "Brake pedal feel and valve operation",
  ]),
  sec(T, "steer", "Steering", [
    "Steering wheel free play within limits",
    "Steering box — leaks, mounting and play",
    "Power steering fluid level and condition",
    "Power steering pump and hoses",
    "Drag link and ball joints",
    "Tie rod and ends",
    "Kingpins and bushes — play",
    "Steering stops set correctly",
    "Steering column and U-joints secure",
    "Wheel alignment / pulling on road test",
  ]),
  sec(T, "frontsusp", "Front Suspension", [
    "Front leaf springs — broken or shifted leaves",
    "Front spring U-bolts torqued",
    "Front spring hangers and shackles",
    "Front spring bushes",
    "Front shock absorbers — leaks and mountings",
    "Front stabiliser bar and links",
    "Front axle beam — cracks and damage",
    "Front air bags / suspension (where fitted)",
    "Front centre bolts intact",
    "Front ride height correct",
  ]),
  sec(T, "rearsusp", "Rear Suspension", [
    "Rear leaf springs / air bags condition",
    "Rear spring U-bolts torqued",
    "Rear hangers, shackles and trunnions",
    "Torque rods / reaction arms and bushes",
    "Rear shock absorbers — leaks and mountings",
    "Levelling valves and linkages",
    "Air suspension lines and fittings",
    "Rear stabiliser bar and links",
    "Tag / lift axle operation (where fitted)",
    "Rear ride height correct and level",
  ]),
  sec(T, "tyres", "Wheels & Tyres", [
    "Steer tyres — tread depth at or above legal minimum",
    "Steer tyres — cuts, bulges and sidewall damage",
    "Drive tyres — tread depth",
    "Drive tyres — damage and irregular wear",
    "Tyre pressures — all positions to spec",
    "Duals matched for size and tread",
    "Valve stems, caps and extensions",
    "Wheel nuts — torque and nut indicators",
    "Rims — cracks, damage and corrosion",
    "Spare wheel secure and serviceable",
  ]),
  sec(T, "chassis", "Chassis, Fifth Wheel & Coupling", [
    "Chassis rails — cracks, bends and repairs",
    "Cross-members and gussets secure",
    "Chassis bolts and rivets tight",
    "Fifth wheel mounting bolts and plate",
    "Fifth wheel jaws, locking mechanism and wear",
    "Fifth wheel greased and release handle working",
    "Tow hitch / drawbar coupling and pin (where fitted)",
    "Rear underrun protection secure",
    "Side guards / under-run rails (where fitted)",
    "Catwalk, steps and grab handles secure",
  ]),
  sec(T, "cabext", "Cab Exterior & Body", [
    "Windscreen — no cracks in driver's view",
    "Wipers and washers operational",
    "Mirrors — all fitted, adjusted, clean",
    "Doors, hinges, locks and seals",
    "Cab mountings and tilt mechanism",
    "Cab tilt lock / safety catch",
    "Mudguards and mudflaps fitted",
    "Reflective / chevron conspicuity tape",
    "Side windows and winders",
    "Body panels, bumper and grille secure",
  ]),
  sec(T, "cabint", "Cab Interior & Driver Controls", [
    "Seat belts — all seats, retract and latch",
    "Driver seat adjustment and suspension",
    "Horn operation",
    "Accelerator pedal returns freely",
    "Brake and clutch pedals — rubbers and travel",
    "Air conditioning operation",
    "Interior lights",
    "Cab clean and free of loose objects",
    "Sleeper berth and restraints (where fitted)",
    "Two-way radio / communication device working",
  ]),
  sec(T, "safety", "Safety Equipment & Road Test", [
    "Fire extinguisher — charged, serviced, secured",
    "Warning triangles (2) on board",
    "First aid kit complete and in date",
    "Wheel chocks on board",
    "Spill kit on board (DG and mine sites)",
    "Reflective vest and PPE for driver",
    "Buggy whip / flag (mine site spec, where required)",
    "Road test — steering, brakes and handling",
    "Road test — no abnormal noises or vibration",
    "Final walk-around, sign-off and defects recorded",
  ]),
];

const R = "i200r";
export const TRAILER_200_SECTIONS = [
  sec(R, "docs", "Documentation & Identification", [
    "Licence disc valid and displayed",
    "Roadworthy / COF certificate valid",
    "Registration plate secure and legible",
    "VIN / chassis number matches documents",
    "Tare, GVM and load limits plate fitted",
    "Service history and previous job cards reviewed",
    "Open defect reports checked",
    "Hubodometer reading recorded",
    "DG / tank / abnormal permits valid (where applicable)",
    "Tank calibration / test certificate valid (tankers)",
  ]),
  sec(R, "kingpin", "Kingpin & Upper Coupler", [
    "Kingpin wear within gauge limits",
    "Kingpin — no cracks, bends or damage",
    "Kingpin securing bolts / welds intact",
    "Upper coupler (skid) plate — flat, no cracks",
    "Upper coupler plate lubricated",
    "Upper coupler mounting to chassis secure",
    "Drawbar eye and bush wear (drawbar trailers)",
    "Drawbar — cracks, bends and pins (where fitted)",
    "Turntable / dolly condition (where fitted)",
    "Coupling height compatible with fleet horses",
  ]),
  sec(R, "legs", "Landing Legs", [
    "Landing legs — straight, no damage",
    "Landing leg feet / sand shoes intact",
    "Crank handle and gearbox operation",
    "Landing leg high / low gear engagement",
    "Cross-shaft and connecting rod",
    "Landing leg mountings and bracing",
    "Landing legs greased",
    "Landing legs fully retracted for travel",
    "Crank handle stowage secure",
    "Legs support trailer without creeping",
  ]),
  sec(R, "chassis", "Chassis & Frame", [
    "Main beams — cracks, bends and repairs",
    "Cross-members secure and undamaged",
    "Gooseneck area — cracks and stress",
    "Welds — no cracking at high-stress points",
    "Chassis bolts and rivets tight",
    "Corrosion within acceptable limits",
    "Outriggers and side rails",
    "Spare wheel carrier secure",
    "Toolbox and mountings secure",
    "Chassis earth / bonding strap (tankers)",
  ]),
  sec(R, "airsupply", "Air Brake System — Supply & Control", [
    "Supply (red) coupling and seal",
    "Service (yellow) coupling and seal",
    "Air lines — chafing, kinking and security",
    "Air tanks drained — no oil or water",
    "Air tank mountings secure",
    "Relay / emergency valve operation",
    "Trailer park brake valve operation",
    "Air leak test — at rest",
    "Air leak test — brakes applied",
    "Breakaway function — brakes apply on disconnect",
  ]),
  sec(R, "brakes", "Brake Foundation", [
    "Brake linings / pads — axle 1",
    "Brake linings / pads — axle 2",
    "Brake linings / pads — axle 3 (where fitted)",
    "Drums / discs — cracks, scoring and wear",
    "Brake chambers and spring brakes — condition",
    "Slack adjusters — stroke within limits",
    "Brake camshafts, bushes and rollers",
    "Brake return springs",
    "Brake dust shields",
    "Brake balance / efficiency (brake test)",
  ]),
  sec(R, "abs", "ABS / EBS & Electrical Connections", [
    "ABS / EBS warning lamp function",
    "ABS / EBS modulator and sensors",
    "ABS / EBS wiring and plug",
    "24V trailer plug(s) — pins and body",
    "Suzie / spiral cables — condition and length",
    "Main wiring harness — chafing and clips",
    "Junction boxes sealed",
    "Earth connections clean and tight",
    "Auxiliary power (reefer / tail-lift) connection",
    "No exposed or taped-over wiring",
  ]),
  sec(R, "lights", "Lighting & Signalling", [
    "Tail lamps",
    "Stop / brake lamps",
    "Direction indicators — rear",
    "Side indicators / repeaters",
    "Side marker lamps — full length",
    "Front position / end-outline marker lamps",
    "Rear fog lamp (where fitted)",
    "Number plate lamp",
    "Reverse lamp (where fitted)",
    "Lamp lenses clean, uncracked and correct colour",
  ]),
  sec(R, "markings", "Reflectors, Markings & Conspicuity", [
    "Rear red reflectors",
    "Side amber reflectors",
    "Front white reflectors",
    "Rear chevron / reflective board",
    "Side conspicuity tape — full length",
    "Rear conspicuity tape",
    "Hazchem / DG placards correct and fitted (DG loads)",
    "Abnormal load signage (where applicable)",
    "Speed / height / length markings correct",
    "Company branding and fleet number legible",
  ]),
  sec(R, "axles", "Axles & Hubs", [
    "Axle beams — cracks, bends and damage",
    "Axle alignment / tracking",
    "Wheel bearings — play and noise",
    "Hub seals — no leaks",
    "Hub caps secure and oil level (oil-bath hubs)",
    "Axle U-bolts torqued",
    "Axle seats and locating pins",
    "Lift axle operation (where fitted)",
    "Steering axle and lock (where fitted)",
    "Hubodometer secure",
  ]),
  sec(R, "airsusp", "Suspension — Air", [
    "Air bags — cracks, chafing and leaks",
    "Air bag mountings and pistons",
    "Levelling valves and linkages",
    "Ride height correct and level",
    "Air suspension lines and fittings",
    "Dump / raise-lower valve operation",
    "Shock absorbers — leaks and mountings",
    "Trailing arms — cracks and bushes",
    "Hanger brackets — cracks and welds",
    "Suspension air tank drained",
  ]),
  sec(R, "mechsusp", "Suspension — Mechanical & Mounts", [
    "Leaf springs — broken or shifted leaves",
    "Spring centre bolts intact",
    "Equaliser / rocker beams",
    "Equaliser bushes and pins",
    "Spring hangers front and rear",
    "Torque / radius rods and bushes",
    "Torque rod adjustment and locking",
    "Spring slippers / wear pads",
    "Bogie mountings to chassis",
    "Suspension greased",
  ]),
  sec(R, "wheels", "Wheels & Rims", [
    "Wheel nuts — torque, axle 1",
    "Wheel nuts — torque, axle 2",
    "Wheel nuts — torque, axle 3 (where fitted)",
    "Wheel nut indicators fitted and aligned",
    "Rims — cracks and damage",
    "Rims — corrosion and stud-hole wear",
    "Wheel studs — none missing or damaged",
    "Wheel spacers / hub-piloting correct",
    "Spare wheel secure and serviceable",
    "Wheel chocks on board",
  ]),
  sec(R, "tyres", "Tyres", [
    "Tread depth at or above legal minimum — all positions",
    "Sidewall cuts, bulges and damage",
    "Irregular wear (alignment / camber / bearing)",
    "Tyre pressures — all positions to spec",
    "Duals matched for size and tread",
    "Valve stems, caps and extensions",
    "Tyres free of embedded stones between duals",
    "Retreads — condition and legal use",
    "Correct load and speed rating",
    "Tyre serial numbers match tyre register",
  ]),
  sec(R, "body", "Body / Deck / Tank Structure", [
    "Deck / floor — holes, rot and damage",
    "Side walls / drop-sides — condition",
    "Headboard / bulkhead — secure and rated",
    "Tipper body / bin — cracks and wear plates",
    "Tank shell — dents, cracks and leaks (tankers)",
    "Tank manholes, lids and seals (tankers)",
    "Reefer body — panels, seals and insulation",
    "Curtains, straps and buckles (tautliners)",
    "Roof — leaks, bows and sheets",
    "Body-to-chassis mountings secure",
  ]),
  sec(R, "doors", "Doors, Tailgates & Hatches", [
    "Rear doors / tailgate — hinges",
    "Rear doors — locks, cam bars and seals",
    "Door hold-back hooks",
    "Tailgate chains and locking pins",
    "Side doors / gates (where fitted)",
    "Hatches and inspection covers",
    "Tail-lift operation and safety (where fitted)",
    "Seals intact — dust / water / temperature",
    "Security seals / locks available",
    "Ladders and access steps secure",
  ]),
  sec(R, "securing", "Load Securing Equipment", [
    "Ratchet straps — condition and rated",
    "Chains and binders — condition and rated",
    "Lashing / tie-down points — secure, not cracked",
    "Twist locks — operation and locking (skeletal)",
    "Stanchions and pins",
    "Load bars / shoring bars",
    "Tarpaulins / nets — no tears",
    "Tarp ropes and rails",
    "Winches and winch bars",
    "Securing equipment stowed when empty",
  ]),
  sec(R, "protection", "Underrun, Side Protection & Mudflaps", [
    "Rear underrun protection — secure and undamaged",
    "Side under-run guards secure (where fitted)",
    "Mudguards fitted",
    "Mudflaps fitted and intact",
    "Spray suppression (where fitted)",
    "Rear bumper / buffer",
    "Step / catwalk guards",
    "Sharp edges and protrusions removed",
    "Spare wheel / toolbox not protruding",
    "Wheel guards / fenders secure",
  ]),
  sec(R, "equip", "Tipping, Discharge & Specialised Equipment", [
    "Tipping ram — leaks and mountings",
    "Hydraulic hoses and fittings",
    "Hydraulic oil level (tipper / pump)",
    "Tipping safety prop / stay available",
    "Tank discharge valves and caps (tankers)",
    "Emergency shut-off / foot valve (tankers)",
    "Vapour recovery / vent system (tankers)",
    "Reefer unit operation and temperature set point",
    "Reefer fuel level and alarms",
    "Pneumatic / bulk discharge system (where fitted)",
  ]),
  sec(R, "final", "Safety, Environmental & Final Check", [
    "Fire extinguisher on trailer (DG / tanker)",
    "Spill kit on board (DG and mine sites)",
    "No oil, fuel or hydraulic leaks under trailer",
    "Earth / anti-static strap (tankers)",
    "Trailer clean — no loose material or spillage",
    "Coupling test — tug test with horse",
    "Brake test coupled — trailer holds",
    "All lights tested coupled to horse",
    "Road test — tracking, noise and brake balance",
    "Final walk-around, sign-off and defects recorded",
  ]),
];

export const INSPECTION_POINT_COUNT = 200;

export const get200PointInspection = (assetType) =>
  assetType === "trailer" ? TRAILER_200_SECTIONS : TRUCK_200_SECTIONS;
